version: "3"
services:
  mysql:
    image: docker_mysql_mysql # イメージの名前
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root   #コンテナ内のMySQLを起動する際のパスワードを設定
      - TZ='Asia/Tokyo'
    ports:
      - '3306:3306'
    container_name: docker_mysql_mysql_1
    build: ./docker/mysql

  golang: # service名
    build: ./docker/golang # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    ports:
      - '1323:1323'
    volumes:
      - .:/go/src/github.com/Yukata-team/GoRela-server # マウントディレクトリ指定
    command: go run main.go
